version: "3.9"

services:
  jupetrack:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jupetrack
    ports:
      - "3040:3040"
    restart: always
    environment:
      - INTERNAL_API_URL=http://localhost:3041
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/data:/app/backend/data
